% load rsdepth data from the simulator
load('rsdepth_lidar.mat');

% all the necessary variables for number of points generated by the
% Lidar,the sensor position and the range of the lidar are modified the the
% CreateRobot.m file and then a SD of 0.2 was used to generate the rsdepth
% array, robot did not move when the readings were taken.
depth_1 = dataStore.rsdepth(1,2:end);

% get robot pose from truthpose, robot did not move during the readings
robotPose = dataStore.truthPose(1 , 2:4);

% all significant map values taken from box_map.txt
map = [ 0 2 2 0;
        0 2 -2 0;
        0 -2 2 0;
        0 -2 -2 0];

sensor = [0 0.08]; %from qn
angles = linspace(deg2rad(27),deg2rad(-27),55); %from qn

% generate the array of predicted depths
depth_2 = depthPredict(robotPose, map, sensor, angles')';





% plot the predicted depths against the simulated rsdepth
figure;
hold on;
grid on;
    
% Plot the first depth array in blue
plot(angles, depth_1, 'b-o', 'MarkerSize', 3, 'LineWidth', 1.5, 'DisplayName', 'rsdepth');
    
% Plot the second depth array in red
plot(angles, depth_2, 'r-s', 'MarkerSize', 3, 'LineWidth', 1.5, 'DisplayName', 'predicted depth');
    
% Labels and title
xlabel('Angle (radians)');
ylabel('Depth (meters)');
title('Comparison of Predicted Depth Measurements');
    
% Add legend
legend('show', 'Location', 'best');
    
hold off;